robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500

  # Position Controllers needs to be tuned ---------------------------------------
  lbr4_j0_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr4_j0
    pid: {p: 1000.0, i: 0.0, d: 1.0}
  lbr4_j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr4_j1
    pid: {p: 5000.0, i: 0.0, d: 1.0}
  lbr4_j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr4_j2
    pid: {p: 3000.0, i: 0.0, d: 1.0}
  lbr4_j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr4_j3
    pid: {p: 5000.0, i: 0.0, d: 1.0}
  lbr4_j4_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr4_j4
    pid: {p: 3000.0, i: 0.0, d: 1.0}
  lbr4_j5_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr4_j5
    pid: {p: 3000.0, i: 0.0, d: 1.0}
  lbr4_j6_position_controller:
    type: effort_controllers/JointPositionController
    joint: lbr4_j6
    pid: {p: 1000.0, i: 0.0, d: 1.0}